# Generated by Django 5.2.1 on 2025-05-20 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("content", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="imagecontent",
            name="optimized_image_webp",
            field=models.ImageField(
                blank=True,
                help_text="The optimized WebP version of the image.",
                null=True,
                upload_to="lesson_images_optimized/",
            ),
        ),
    ]
