# Generated by Django 5.2.1 on 2025-05-16 22:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Course",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(help_text="Title of the course.", max_length=200),
                ),
                (
                    "slug",
                    models.SlugField(
                        help_text="URL-friendly identifier for the course.",
                        max_length=200,
                        unique=True,
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True, help_text="Brief overview of the course."
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        blank=True,
                        help_text="Thumbnail or banner image for the course.",
                        null=True,
                        upload_to="course_images/",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name_plural": "Courses",
                "ordering": ["title"],
            },
        ),
        migrations.CreateModel(
            name="Module",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(help_text="Title of the module.", max_length=200),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True, help_text="Brief description of the module."
                    ),
                ),
                (
                    "order",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="The order of this module within the course.",
                    ),
                ),
                (
                    "course",
                    models.ForeignKey(
                        help_text="The course this module belongs to.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="modules",
                        to="courses.course",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Modules",
                "ordering": ["order"],
            },
        ),
        migrations.CreateModel(
            name="Lesson",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(help_text="Title of the lesson.", max_length=200),
                ),
                (
                    "slug",
                    models.SlugField(
                        help_text="URL-friendly identifier for the lesson.",
                        max_length=200,
                    ),
                ),
                (
                    "order",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="The order of this lesson within the module.",
                    ),
                ),
                (
                    "module",
                    models.ForeignKey(
                        help_text="The module this lesson belongs to.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lessons",
                        to="courses.module",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Lessons",
                "ordering": ["order"],
                "unique_together": {("module", "slug")},
            },
        ),
    ]
