# Generated by Django 5.2.1 on 2025-05-20 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="course",
            name="optimized_image_webp",
            field=models.ImageField(
                blank=True,
                help_text="The optimized WebP version of the course image.",
                null=True,
                upload_to="course_images_optimized/",
            ),
        ),
    ]
